version: "3.7"
services:
#  db:
#    image: postgres:latest
#    restart: always
#    volumes:
#      - /var/lib/docker/volumes/colibris-overview/pgdata:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=colibrisoverview
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
#  cache:
#    image: redis:last
#    restart: always
#    ports:
#      - "6379:6379"

  server:
    image: colibris-overview:latest
    build:
      context: .
      target: server
#    environment:
#      - DATABASE_NAME=colibrisoverview
#      - DATABASE_HOST=db
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
#      - CACHE_HOST=cache
#    command: >
#      bash -c "wait-for-it db:5432 -t 10 -s &&
#               wait-for-it cache:6379 -t 10 -s &&
#               colibris-overview runserver"
    ports:
      - "8888:8888"
#    depends_on:
#      - db
#      - cache

#  worker:
#    image: colibris-overview:worker-latest
#    build:
#      context: .
#      target: worker
#    environment:
#      - DATABASE_NAME=colibrisoverview
#      - DATABASE_HOST=db
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
#      - CACHE_HOST=cache
#    command: >
#      bash -c "wait-for-it db:5432 -t 10 -s &&
#               wait-for-it cache:6379 -t 10 -s &&
#               colibris-overview runworker"
#    ports:
#      - "8888:8888"
#    depends_on:
#      - db
#      - cache
